---
- name: Setup Repository
  hosts: cloud
  become: true
  tasks:
  - name: Add key to keyring.
    ansible.builtin.get_url:
      url: https://pkgs.zabbly.com/key.asc
      dest: /etc/apt/keyrings/zabbly.asc
  - name: Create apt source file.
    copy:
      dest: /etc/apt/sources.list.d/zabbly-incus-stable.sources
      content: |
        Enabled: yes
        Types: deb
        URIs: https://pkgs.zabbly.com/incus/stable
        Suites: jammy
        Components: main
        Architectures: amd64
        Signed-By: /etc/apt/keyrings/zabbly.asc
