---
- name: Update all packages.
  hosts: clouds
  become: true
  tasks:
    - name: Update cache and all packages.
      ansible.builtin.apt:
        name: "*"
        state: latest
        cache_valid_time: 30
        update_cache: yes
