---
- name: Setup basic
  hosts: all
  become: true
  tasks:
  - name: Update all packages.
    ansible.builtin.apt:
      name: "*"
      update_cache: yes
      state: latest
  - name: Install net-tools
    ansible.builtin.apt:
      name: net-tools
      state: latest
  - name: Install mc
    ansible.builtin.apt:
      name: mc
      state: latest
