---
- name: Remove all Incus packages.
  hosts: cloud
  become: true
  tasks:
  - name: Remove UI
    ansible.builtin.apt:
      name: incus-ui-canonical
      state: absent
  - name: Remove Incus
    ansible.builtin.apt:
      name: incus
      state: absent
  - name: Remove repository from apt.
    ansible.builtin.file:
      path: /etc/apt/sources.list.d/zabbly-incus-stable.sources
      state: absent
  - name: Update cache and packages.
    ansible.builtin.apt:
      name: "*"
      update_cache: yes
      state: latest
  - name: Remove dependencies that are no longer required.
    ansible.builtin.apt:
      autoremove: yes
